### ISSUE TITLE
Error in localnum function

### ISSUE THREAD

**Issue by NarubyRiverlione** [digipedro/mom_quant#10]
> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toLocaleString')
>     at localnum (index.html:286:22)
>     at Vue.buildTable (index.html:844:54)
>     at Vue.loadMarket (index.html:1043:71)

```
  function localnum(num) {
          if (isNaN(num))
              return "---";
          return num.toLocaleString(undefined, { minimumFractionDigits: 3, maximumFractionDigits: 3 });
      }
```

Test case : no tasks as showing up for Sabatier reactor or chem lab due to this error.

I'm on Mac OS 12.4 with **Chrome  103.0.5060.134**  and my locales 
```
navigator.languages
(3) ['nl', 'en-GB', 'en']
```

**No error in Safari !**

**Comment by digipedro** [comment]
I think this is due to the data only partially loading for some reason, but I've added protection for null values to this function so it won't completely halt the script.
