### ISSUE TITLE
Salvage Rover task ROI calc should use Electronic Parts, not Electronic Bits

### ISSUE THREAD

**Issue by trantjd** [digipedro/mom_quant#15]
The current ROI calculation for Salvage Rover task (both low level and high level) in the Machine Shop assumes that the output includes Electronic Bits as opposed to the actual output of Electronic Parts listed in the game.

The current price of Electronic Bits is 0.076 Dusk while the last sold price of Electronic Parts is 82 Dusk, making the 3.3-3.6 average output of the task actually worth at least 270 Dusk more (on average).

Here's the current output entry for Electronic Bits in the ROI calculator:
![image](https://user-images.githubusercontent.com/5199132/188517219-c652a307-5b63-4c25-8065-fd4e81b70d58.png)

And here's the Reward Per Task listed in game (in an Epic Lvl 3 Machine Shop):
![image](https://user-images.githubusercontent.com/5199132/188517171-65875a90-089d-41c0-bbc9-6a6efa4dff1d.png)

**Comment by trantjd** [comment]
And just as a quick confirmation, this was the outcome of my task:
![image](https://user-images.githubusercontent.com/5199132/188606982-56c1d9ef-4ae4-4092-865c-b5027c8cafd5.png)

**Comment by digipedro** [comment]
Typo in the resources list. Thanks for pointing this out!
