### ISSUE TITLE
Express Library Output in terms of Novice Research instead of Dusk 

### ISSUE THREAD

**Issue by millorfernandes** [digipedro/mom_quant#8]
Express Library Output in terms of Novice Research instead of Dusk. 

This is important for those high tier library tasks (303, 404, 505). As there is no market (or low liquidity) for research above Apprentice, its is difficult to arbitrate value of high tier library tasks.

**Comment by digipedro** [comment]
I think this would be misleading for people who use the site to determine what the most profitable tasks are- they'd be stuck with research  they can't sell (unless there is some way to break them down to novice research papers in-game). It is still valuable for people to know the cost of running the task, but if there is no market for them then there should be no market value listed, people need to decide for themselves if it's worth it for leveling up.
